### ISSUE TITLE
template error while templating string: Encountered unknown tag ’s’

### ISSUE THREAD

**Issue by vladdancer** [geerlingguy/ansible-role-mailhog#1]
Thanks for useful role!

I think it's related to the copy module only, but i don't even know what thing caused this issue(

on task: Copy mailhog init script into place
Ubuntu 14.04, connection: local, sudo: true, ansible: 1.8

**Comment by geerlingguy** [comment]
@vladdancer - Can you paste the full error from a playbook run here, so I can get any extra info on the run?

I haven't seen this issue before, and it seems the copy task wouldn't be evaluating any conditionals or vars that could cause that particular error :/

**Comment by vladdancer** [comment]
Thanks for reply @geerlingguy. I'll try to reproduce and paste log here at the end of the week.

**Comment by geerlingguy** [comment]
Closing this issue—please let me know if you can reproduce it.
