### ISSUE TITLE
MailHog v0.2.0

### ISSUE THREAD

**Issue by verschoof** [geerlingguy/ansible-role-mailhog#12]
Hi @geerlingguy 

I see that MailHog v0.2.0 is released on march. Is it possible to update your role to the v0.2.0 version?
I see there is a PR #11 that updates it.

Do you need any help? Should it be tested or something else?

Let me know =)

**Comment by geerlingguy** [comment]
This has been merged. Thanks!

**Comment by verschoof** [comment]
Alirght thanks! (don't forget to tag it :D)

**Comment by geerlingguy** [comment]
1.1.0 just released, and tests are green :)
