### ISSUE TITLE
Set SMTP options

### ISSUE THREAD

**Issue by darylteo** [geerlingguy/ansible-role-mailhog#18]
I'd like to set SMTP settings for MailHog.

https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md

Only way I can see of achieving this is to modify the template to apply CLI options to the daemonize command.

**Comment by oxyc** [comment]
@geerlingguy I was browsing trellis code a few days ago and noticed they had the convention of allowing users to use jinja template inheritance for making more advanced customizations. Eg. https://github.com/roots/trellis/tree/master/roles/sshd#customize-via-child-templates

Might be worth considering for requests such as this.

**Comment by geerlingguy** [comment]
@oxyc - Interesting... that would definitely be helpful in this role and many others. I hadn't noticed that the same awesome inheritance that I use in Twig/PHP is also inherited from Jinja!
