### ISSUE TITLE
Failed to validate the SSL

### ISSUE THREAD

**Issue by valugi** [geerlingguy/ansible-role-mailhog#19]
Hi,
I was trying to install the mailhog role on a Centos7, although I think this error is not related with the OS, maybe not even related with the role itself. This came from the default config, I see that it is trying to install 0.2.1 not the latest 1.0.0. 
Any ideas?

TASK [geerlingguy.mailhog : Download MailHog and mhsendmail binaries.] *********
failed: [default] (item={u'url': u'https://github.com/mailhog/MailHog/releases/download/v0.2.1/MailHog_linux_amd64', u'dest': u'/opt/mailhog/mailhog'}) => {"failed": true, "item": {"dest": "/opt/mailhog/mailhog", "url": "https://github.com/mailhog/MailHog/releases/download/v0.2.1/MailHog_linux_amd64"}, "msg": "Failed to validate the SSL certificate for github-production-release-asset-2e65be.s3.amazonaws.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
failed: [default] (item={u'url': u'https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64', u'dest': u'/opt/mailhog/mhsendmail'}) => {"failed": true, "item": {"dest": "/opt/mailhog/mhsendmail", "url": "https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64"}, "msg": "Failed to validate the SSL certificate for github-production-release-asset-2e65be.s3.amazonaws.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by valugi** [comment]
And as a side not, should the path to 0.2.1 be hardcoded?

**Comment by kajmagnus** [comment]
If its' a default config, I suppose any certs are self signed, and this is expected to happen?  (you wrote: *"This came from the default config"* )
