### ISSUE TITLE
Centos6 needs daemonize

### ISSUE THREAD

**Issue by toddejohnson** [geerlingguy/ansible-role-mailhog#20]
I'm using this via drupalvm with CentOS 6 and found that the init script needs daemonize which is missing. I'd suggest adding a dependency for the epel package daemonize

**Comment by geerlingguy** [comment]
@toddejohnson - This role has an explicit dependency on the `geerlingguy.daemonize` role: https://github.com/geerlingguy/ansible-role-mailhog/blob/master/meta/main.yml#L2-L3

You will need to use that role before this one in your playbook to make sure daemonize is available.
