### ISSUE TITLE
Failed determining service state

### ISSUE THREAD

**Issue by rainercedric23** [geerlingguy/ansible-role-mailhog#5]
Hi can you help me with this issue? I am currently installing mailhog with my vagrant. Already added    mailhog in my vars and roles directory. This is the error when I prevision:

==> default: TASK: [mailhog | Ensure mailhog is enabled and will start on boot.] **********\* 
==> default: failed: [192.168.56.99] => {"failed": true}
==> default: msg: failed determining service state, possible typo of service name?

**Comment by pulponair** [comment]
check /etc/init.d/mailhog for windows line endings. 
and
check if you set the correct mailhog plattform: amd64 vs 386

**Comment by geerlingguy** [comment]
@rainercedric23 - What guest OS are you using? Also, what host OS?

**Comment by rainercedric23** [comment]
hi [@geerlinguy](https://github.com/geerlingguy), I am using CentOS version 6.5

**Comment by geerlingguy** [comment]
Closing this old issue—if you believe this is still an issue, please let me know and I'll reopen.
